[MOSIP-31575] Updated docker file.
mosip/audit-manager pull request #143
Opened 2024-03-14 13:06 UTC by abhishek8shankar

2024-04-02 11:40 UTC, syedsalman3753 approved these changes

2024-04-11 12:31 UTC, ckm007 requested changes
Please keep comments as is. In case of common comment add all the statements after that comment and the redundant comment can be removed.

2024-04-12 13:01 UTC, ckm007 approved these changes

2024-04-12 13:32 UTC, LoganathanSekar7627 approved these changes

2024-04-19 06:13 UTC, closed without merging